/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto.pkg1.so.errasti.francisco;

import EDD.Cola;
import Objects.Simulacion;
import EDD.Semaforo;
import Objects.Proceso;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;

/**
 *
 * @author Dell
 */
public class LoadArchiveUI extends javax.swing.JFrame {
    
    private ProcessConfUI creacion;
    /**
     * Creates new form LoadArchiveUI
     */
    public LoadArchiveUI() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.creacion=new ProcessConfUI();
    }
    
public MainUI restablecerEstado(String path) {
    try (BufferedReader reader = new BufferedReader(new FileReader(path))) {
        Semaforo semaforo = null;
        Cola colaL = null;
        Cola colaT = null;
        Cola colaB = null;
        int cicloReloj = 0;
        int numProcesadores = 0;
        Proceso en1 = null;
        Proceso en2 = null;
        Proceso en3 = null;

        String line;
        while ((line = reader.readLine()) != null) {
            if (line.startsWith("Semáforo: ")) {
                semaforo = new Semaforo();
            } else if (line.startsWith("Cola L: ")) {
                colaL = new Cola();
            } else if (line.startsWith("Cola T: ")) {
                colaT = new Cola();
            } else if (line.startsWith("Cola B: ")) {
                colaB = new Cola();
            } else if (line.startsWith("Ciclo Reloj: ")) {
                cicloReloj = Integer.parseInt(line.substring(13).trim());
            } else if (line.startsWith("Número de CPUs: ")) {
                numProcesadores = Integer.parseInt(line.substring(16).trim());
            } else if (line.startsWith("CPU1 Proceso Actual: ")) {
                String procesoData = line.substring(21).trim();
                if (!procesoData.equals("null")) {
                    en1 = new Proceso("Proceso1", 10, "CPU", 1);
                }
            } else if (line.startsWith("CPU2 Proceso Actual: ")) {
                String procesoData = line.substring(21).trim();
                if (!procesoData.equals("null")) {
                    en2 = new Proceso("Proceso2", 15, "CPU", 2);
                }
            } else if (line.startsWith("CPU3 Proceso Actual: ")) {
                String procesoData = line.substring(21).trim();
                if (!procesoData.equals("null")) {
                    en3 = new Proceso("Proceso3", 20, "CPU", 3);
                }
            }
        }

        if (semaforo == null) semaforo = new Semaforo();
        if (colaL == null) colaL = new Cola();
        if (colaT == null) colaT = new Cola();
        if (colaB == null) colaB = new Cola();

        Simulacion simulacion = new Simulacion(semaforo, colaL, colaT, colaB, cicloReloj, numProcesadores, en1, en2, en3);

        if (numProcesadores == 2) {
            return new MainUI(
                simulacion.getCicloReloj(),
                simulacion.getNumProcesadores(),
                simulacion.getColaL(),
                simulacion.getColaB(),
                simulacion.getColaT(),
                simulacion.getPen1(),
                simulacion.getPen2(),
                simulacion.getSemaforo()
            );
        } else if (numProcesadores == 3) {
            return new MainUI(
                simulacion.getCicloReloj(),
                simulacion.getNumProcesadores(),
                simulacion.getColaL(),
                simulacion.getColaB(),
                simulacion.getColaT(),
                simulacion.getPen1(),
                simulacion.getPen2(),
                simulacion.getPen3(),
                simulacion.getSemaforo()
            );
        } else {
            System.err.println("Número de CPUs no válido: " + numProcesadores);
        }
    } catch (IOException e) {
        e.printStackTrace();
    } catch (NumberFormatException e) {
        System.err.println("Error al convertir un número en el archivo.");
        e.printStackTrace();
    }
    return null;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        SavedProcessButt = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        LoadProcessButt = new javax.swing.JButton();
        StartProcessButt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Swis721 Blk BT", 0, 14)); // NOI18N
        jLabel1.setText("BIENVENIDOS A LA SIMULACION DE PLANIFICACIÓN");

        jLabel2.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        jLabel2.setText("Hecho por Asier Errasti y Jose Francisco");

        SavedProcessButt.setBackground(new java.awt.Color(204, 204, 255));
        SavedProcessButt.setText("Cargar procesos guardados");
        SavedProcessButt.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(51, 0, 204)));

        jLabel3.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        jLabel3.setText("Seleccione una opción:");

        LoadProcessButt.setBackground(new java.awt.Color(204, 204, 255));
        LoadProcessButt.setText("Cargar nuevos procesos");
        LoadProcessButt.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(51, 0, 204)));

        StartProcessButt.setBackground(new java.awt.Color(204, 204, 255));
        StartProcessButt.setText("Iniciar nuevos procesos");
        StartProcessButt.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(51, 0, 204)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LoadProcessButt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(StartProcessButt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SavedProcessButt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(205, 205, 205))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(33, 33, 33)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(SavedProcessButt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(LoadProcessButt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(StartProcessButt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoadArchiveUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoadArchiveUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoadArchiveUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoadArchiveUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoadArchiveUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoadProcessButt;
    private javax.swing.JButton SavedProcessButt;
    private javax.swing.JButton StartProcessButt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
