/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto.pkg1.so.errasti.francisco;

/**
 *
 * @author Dell
 */
public class CiclosRelojConfUI extends javax.swing.JFrame {

    private MainUI sim;

    /**
     * Creates new form CiclosRelojConfUI
     */
    public CiclosRelojConfUI(MainUI sim) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.sim = sim;

        
        CiclosTF.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            CiclosTFMouseClicked(evt);
        }
    });
    }
    
    private CiclosRelojConfUI() {
        throw new UnsupportedOperationException("Not supported");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CiclosBackgroundPanel = new javax.swing.JPanel();
        TitleLab = new javax.swing.JLabel();
        Lab1 = new javax.swing.JLabel();
        CiclosTF = new javax.swing.JTextField();
        AplicarButt = new javax.swing.JButton();
        BacktoMainUIButt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CiclosBackgroundPanel.setBackground(new java.awt.Color(255, 51, 153));

        TitleLab.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        TitleLab.setText("Bienvenido a la configuración de cilos de reloj");

        Lab1.setText("Introduzca la nueva duración de un ciclo de reloj en milisegundos:");

        CiclosTF.setForeground(new java.awt.Color(204, 204, 204));
        CiclosTF.setText("Ej: 3000");

        AplicarButt.setBackground(new java.awt.Color(102, 255, 102));
        AplicarButt.setText("Aplicar");
        AplicarButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AplicarButtActionPerformed(evt);
            }
        });

        BacktoMainUIButt.setBackground(new java.awt.Color(255, 255, 153));
        BacktoMainUIButt.setText("Volver");
        BacktoMainUIButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BacktoMainUIButtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CiclosBackgroundPanelLayout = new javax.swing.GroupLayout(CiclosBackgroundPanel);
        CiclosBackgroundPanel.setLayout(CiclosBackgroundPanelLayout);
        CiclosBackgroundPanelLayout.setHorizontalGroup(
            CiclosBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CiclosBackgroundPanelLayout.createSequentialGroup()
                .addGroup(CiclosBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CiclosBackgroundPanelLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(TitleLab))
                    .addGroup(CiclosBackgroundPanelLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(CiclosBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Lab1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CiclosTF)))
                    .addGroup(CiclosBackgroundPanelLayout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(AplicarButt, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CiclosBackgroundPanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(BacktoMainUIButt)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        CiclosBackgroundPanelLayout.setVerticalGroup(
            CiclosBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CiclosBackgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitleLab)
                .addGap(18, 18, 18)
                .addComponent(Lab1)
                .addGap(39, 39, 39)
                .addComponent(CiclosTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(AplicarButt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(BacktoMainUIButt)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CiclosBackgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CiclosBackgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BacktoMainUIButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BacktoMainUIButtActionPerformed
        this.setVisible(false);
        this.sim.setVisible(true);
    }//GEN-LAST:event_BacktoMainUIButtActionPerformed

    private void AplicarButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AplicarButtActionPerformed
        this.sim.setCicloreloj(Integer.parseInt(CiclosTF.getText()));
        this.sim.actualizarCiclo();
        this.setVisible(false);
        this.sim.setVisible(true);
    }//GEN-LAST:event_AplicarButtActionPerformed

    
    private void CiclosTFMouseClicked(java.awt.event.MouseEvent evt) {                                          
    CiclosTF.setText("");
    CiclosTF.setForeground(new java.awt.Color(0, 0, 0));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CiclosRelojConfUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CiclosRelojConfUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CiclosRelojConfUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CiclosRelojConfUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CiclosRelojConfUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AplicarButt;
    private javax.swing.JButton BacktoMainUIButt;
    private javax.swing.JPanel CiclosBackgroundPanel;
    private javax.swing.JTextField CiclosTF;
    private javax.swing.JLabel Lab1;
    private javax.swing.JLabel TitleLab;
    // End of variables declaration//GEN-END:variables
}
