/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto.pkg1.so.errasti.francisco;

/**
 *
 * @author Dell
 */
public class NumCPUConfUI extends javax.swing.JFrame {

    private LoadArchiveUI carga;
    /**
     * Creates new form NumCPUConfUI
     */
    public NumCPUConfUI(LoadArchiveUI c) {
        this.carga=c;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setSize(445,345);
        
        CantCPUTF.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            CantCPUTFMouseClicked(evt);
        }
    });
        CiclosTF.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            CiclosTFMouseClicked(evt);
        }
    });
    }

    private NumCPUConfUI() {
        throw new UnsupportedOperationException("Not supported yet.");
    }
        
    public int getCPU(){
        return Integer.parseInt(CantCPUTF.getText());
    }
    
    public int getDuracion(){
        return Integer.parseInt(CiclosTF.getText());
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TittleLab = new javax.swing.JLabel();
        Lab1 = new javax.swing.JLabel();
        CantCPUTF = new javax.swing.JTextField();
        Lab2 = new javax.swing.JLabel();
        CiclosTF = new javax.swing.JTextField();
        AplicarButt = new javax.swing.JButton();
        BacktoMainUIButt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TittleLab.setText("Bienvenido a la configuración de la cantidad de procesadores");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(TittleLab)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TittleLab)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        Lab1.setText("Cantidad de procesadores activos:");

        CantCPUTF.setForeground(new java.awt.Color(204, 204, 204));
        CantCPUTF.setText("Ej: 1");

        Lab2.setText("Ciclo de reloj (Milisegundos):");

        CiclosTF.setForeground(new java.awt.Color(204, 204, 204));
        CiclosTF.setText("Ej: 3000");

        AplicarButt.setText("Aplicar");
        AplicarButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AplicarButtActionPerformed(evt);
            }
        });

        BacktoMainUIButt.setText("Volver");
        BacktoMainUIButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BacktoMainUIButtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 55, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Lab2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CiclosTF))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Lab1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CantCPUTF, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BacktoMainUIButt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AplicarButt)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lab1)
                    .addComponent(CantCPUTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lab2)
                    .addComponent(CiclosTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AplicarButt)
                    .addComponent(BacktoMainUIButt))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AplicarButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AplicarButtActionPerformed
        ProcessConfUI pc = new ProcessConfUI(this.getCPU(),this.getDuracion());
        pc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AplicarButtActionPerformed

    private void BacktoMainUIButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BacktoMainUIButtActionPerformed
        this.setVisible(false);
        carga.setVisible(true);
    }//GEN-LAST:event_BacktoMainUIButtActionPerformed

    
    private void CantCPUTFMouseClicked(java.awt.event.MouseEvent evt) {                                          
    CantCPUTF.setText("");
    CantCPUTF.setForeground(new java.awt.Color(0, 0, 0));
    }
    private void CiclosTFMouseClicked(java.awt.event.MouseEvent evt) {                                          
    CiclosTF.setText("");
    CiclosTF.setForeground(new java.awt.Color(0, 0, 0));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NumCPUConfUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NumCPUConfUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NumCPUConfUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NumCPUConfUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NumCPUConfUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AplicarButt;
    private javax.swing.JButton BacktoMainUIButt;
    private javax.swing.JTextField CantCPUTF;
    private javax.swing.JTextField CiclosTF;
    private javax.swing.JLabel Lab1;
    private javax.swing.JLabel Lab2;
    private javax.swing.JLabel TittleLab;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
