/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto.pkg1.so.errasti.francisco;

import javax.swing.ButtonGroup;

/**
 *
 * @author Dell
 */
public class PoliticasConfUI extends javax.swing.JFrame {

    private MainUI sim;

    /**
     * Creates new form PoliticasConfUI
     */
    
    public PoliticasConfUI() {
        initComponents();
    }
    public PoliticasConfUI(MainUI sim) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setSize(600,400);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BacktoMainUIButt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        FCFSButt = new javax.swing.JButton();
        SPNButt = new javax.swing.JButton();
        RRButt = new javax.swing.JButton();
        HRRNButt = new javax.swing.JButton();
        SRTButt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        BacktoMainUIButt.setBackground(new java.awt.Color(255, 255, 153));
        BacktoMainUIButt.setText("Volver");
        BacktoMainUIButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BacktoMainUIButtActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        jLabel1.setText("Bienvenido a la configuración de la política de vaciado");

        FCFSButt.setBackground(new java.awt.Color(255, 102, 102));
        FCFSButt.setText("FCFS");
        FCFSButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FCFSButtActionPerformed(evt);
            }
        });

        SPNButt.setBackground(new java.awt.Color(255, 153, 0));
        SPNButt.setText("SPN");
        SPNButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SPNButtActionPerformed(evt);
            }
        });

        RRButt.setBackground(new java.awt.Color(255, 153, 102));
        RRButt.setText("RR");
        RRButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RRButtActionPerformed(evt);
            }
        });

        HRRNButt.setBackground(new java.awt.Color(255, 204, 153));
        HRRNButt.setText("HRRN");
        HRRNButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HRRNButtActionPerformed(evt);
            }
        });

        SRTButt.setBackground(new java.awt.Color(255, 255, 204));
        SRTButt.setText("SRT");
        SRTButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SRTButtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(BacktoMainUIButt))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SPNButt)
                            .addComponent(FCFSButt)
                            .addComponent(RRButt)
                            .addComponent(HRRNButt)
                            .addComponent(SRTButt))))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(FCFSButt)
                .addGap(34, 34, 34)
                .addComponent(SPNButt)
                .addGap(34, 34, 34)
                .addComponent(RRButt)
                .addGap(32, 32, 32)
                .addComponent(HRRNButt)
                .addGap(34, 34, 34)
                .addComponent(SRTButt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(BacktoMainUIButt)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BacktoMainUIButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BacktoMainUIButtActionPerformed
        this.sim.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BacktoMainUIButtActionPerformed

    private void FCFSButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FCFSButtActionPerformed
        this.sim.setPolitica("FCFS");
        javax.swing.JOptionPane.showMessageDialog(this, "Se aplicó la política FCFS");
        this.sim.cambio();
        this.sim.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_FCFSButtActionPerformed

    private void SPNButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SPNButtActionPerformed
        this.sim.setPolitica("SPN");
        javax.swing.JOptionPane.showMessageDialog(this, "Se aplicó la política SPN");
        this.sim.cambio();
        this.sim.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_SPNButtActionPerformed

    private void HRRNButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HRRNButtActionPerformed
        this.sim.setPolitica("HRRN");
        javax.swing.JOptionPane.showMessageDialog(this, "Se aplicó la política HRRN");
        this.sim.cambio();
        this.sim.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_HRRNButtActionPerformed

    private void RRButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RRButtActionPerformed
        this.sim.setPolitica("RR");
        javax.swing.JOptionPane.showMessageDialog(this, "Se aplicó la política RR");
        this.sim.cambio();
        this.sim.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_RRButtActionPerformed

    private void SRTButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SRTButtActionPerformed
        this.sim.setPolitica("SRT");
        javax.swing.JOptionPane.showMessageDialog(this, "Se aplicó la política SRT");
        this.sim.cambio();
        this.sim.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_SRTButtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PoliticasConfUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PoliticasConfUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PoliticasConfUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PoliticasConfUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PoliticasConfUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BacktoMainUIButt;
    private javax.swing.JButton FCFSButt;
    private javax.swing.JButton HRRNButt;
    private javax.swing.JButton RRButt;
    private javax.swing.JButton SPNButt;
    private javax.swing.JButton SRTButt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
